CREATE TABLE Table1 (Id INT PRIMARY KEY IDENTITY(1,1), Name VARCHAR(50), Description VARCHAR(300), CreateDate DATETIME DEFAULT GETDATE())

CREATE TABLE Table2 (Id INT PRIMARY KEY IDENTITY(1,1), IsActive BIT, IdTable1 INT FOREIGN KEY REFERENCES Table1(Id))